### [ 데이터 전처리를 위한 인코딩 ]  
* 컬럼 중 문자형/범주형인 데이터를 숫자로 변환하는 작업
* 컴퓨터가 분석 및 학습을 하기 쉽도록 변환
* 종류
    * 정수 인코딩 또는 정수 라벨링 
    * 원 핫 인코딩

In [5]:
# 모듈 로딩
import pandas as pd             ## 데이터 분석용 패키지
import numpy as np              ## 배열을 파이썬언어로 구현한 패키지
                                ## pandas에서 데이터 저장을 numpy의 배열로 함!!!
import sys
sys.path.append(r'C:\Users\KDT-008\Desktop\KDT_14\[2]PANDAS\comm')
from utils import data_info

In [6]:
## 데이터 준비 및 DF 인스턴스 생성
DATA_FILE = '../../DATA/iris.csv'

## 첫번째 줄 : 컬럼명 OK, 구분자 : 쉼표/콤마 OK
irisDF = pd.read_csv(DATA_FILE)

In [10]:
## DF 인스턴스 확인
data_info(irisDF)

 ======================
-> 요약정보---
======================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

======================
-> 실제 데이터
======================
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
     sepal.length  sepal.width  petal.length  petal.width    variety
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

======================
-> 컬럼별 정보
======================
        sepal.length  sepal.width  petal.length  petal.width variety
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  Setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [11]:
## 실제 데이터 일부
irisDF.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa

- 방법1) variety 컬럼을 object ==> 숫자/정수 라벨 인코딩

In [15]:
## 품종명에 설정될 값 맵핑

irisDF_map = {
    "Setosa": 0,
    "Versicolor": 1,
    "Virginica": 2
}

## 결측값 NaN에는 함수 적용하여 NaN , 결과를 새로운 컬럼 추가
irisDF["variety_label"] = irisDF['variety'].map(irisDF_map)

## 확인
irisDF.head(3)

   sepal.length  sepal.width  petal.length  petal.width variety  variety_label
0           5.1          3.5           1.4          0.2  Setosa              0
1           4.9          3.0           1.4          0.2  Setosa              0
2           4.7          3.2           1.3          0.2  Setosa              0

- 방법2) 특정 값만 1로 설정하는 인코딩 - 원-핫 인코딩

In [19]:
irisDF2 = pd.get_dummies(irisDF,columns=["variety"],dtype=int)

irisDF2.tail()

,sepal.length,sepal.width,petal.length,petal.width,variety_label,variety_Setosa,variety_Versicolor,variety_Virginica
145,6.7,3.0,5.2,2.3,2,0,0,1
146,6.3,2.5,5.0,1.9,2,0,0,1
147,6.5,3.0,5.2,2.0,2,0,0,1
148,6.2,3.4,5.4,2.3,2,0,0,1
149,5.9,3.0,5.1,1.8,2,0,0,1